version: '2'
services:
  mongodb:
    image: mongo
    hostname: db-mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles
#    volumes:
#      - ./build/libs:/app
#    command: mongoimport --db portal --collection students --type json --file /app/students.json --jsonArray


  mongo_seed:
      image: mongo-seed/.
      links:
        - mongodb



  portalservice:
    image: frolvlad/alpine-oraclejdk8:slim
    working_dir: /app
    volumes:
      - ./build/libs:/app
    command: java -jar /app/my-task-0.1.0.jar
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
#      - redis
    links:
      - mongodb

#  redis:
#    image: redis
#    hostname: db-redis
#  environment:
#    SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/studentsportal
#    SPRING_APPLICATION_NAME: registration-service
